#!perl

use strict;
use warnings FATAL => 'all';
use Uprofiles::db::Uprofiles;
our ($db, $admin, %conf, %lang, $html, %permissions, @WEEKDAYS, @MONTHES, %FORM);

#**********************************************************

=head2 main - show users profiles
 
  Arguments:
    Users
    $stm
    $inner_tpl

=cut

#**********************************************************
sub main {

  #use Uprofiles;

  our Uprofiles $Uprofiles = Uprofiles->new($db, $admin, \%conf);
  my $stm = $Uprofiles->take_data();
  my $inner_tpl;

  # add data to template from $stm
  foreach my $line (@$stm) {
    $inner_tpl .= $html->tpl_show(_include('user_form', 'Uprofiles'), { USER_NAME => ($line->{user_name}), USER_ADDRESS => ($line->{user_address}), USER_EMAIL => ($line->{user_email}) });

    # turn on template module
    require Abills::Templates;

    # print html
    print $html->tpl_show(_include('main_tpl', 'Uprofiles'), { TITLE => "Users information", CONTENT => $inner_tpl });
  }
}

1;

